### ISSUE TITLE
The append/prepend methods are not working if attribute does not exist

### ISSUE THREAD

**Issue by Arattian** [93v/dynatron#11]
**Describe the bug**
The append method and createIfAttributePathDoesNotExist attribute are not working if the attribute does not exist.

```
ValidationException: An operand in the update expression has an incorrect data type
    at call (/Users/misak/myia/consumer-notification-app/node_modules/dynatron/dist/webpack:/dynatron/node_modules/@aws-sdk/client-dynamodb/dist/es/protocols/Aws_json1_0.js:4483:68)
    at step (/Users/misak/myia/consumer-notification-app/node_modules/dynatron/dist/webpack:/dynatron/node_modules/tslib/tslib.es6.js:102:23)
    at Object.next (/Users/misak/myia/consumer-notification-app/node_modules/dynatron/dist/webpack:/dynatron/node_modules/tslib/tslib.es6.js:83:53)
    at a (/Users/misak/myia/consumer-notification-app/node_modules/dynatron/dist/webpack:/dynatron/node_modules/tslib/tslib.es6.js:73:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  __type: 'com.amazon.coral.validate#ValidationException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '7fd19fb3-dc5d-4d19-8cb5-c50d3d1f3859',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  '$input': {
    TableName: 'myia-serverless-api-local-users',
    Key: { id: [Object] },
    ReturnValues: 'ALL_NEW',
    UpdateExpression: 'SET #u_brf=list_append(if_not_exists(#u_brf, :empty_list),:u_brg)',
    ExpressionAttributeNames: { '#u_brf': 'states' },
    ExpressionAttributeValues: { ':u_brg': [Object], ':empty_list': [Object] }
  }
}
```

**To Reproduce**
Execute following code 
```  
  try {
    const result = await db(USERS_TABLE)
      .update({ id: user.id })
      .append("states", [{ timestamp: Date.now(), state: stateId }], true)
      .returnValues("ALL_NEW")
      .$();
    console.log({ result });
  } catch (error) {
    console.log(error);
  }
```

**Expected behavior**
The code above should work and create an attribute if not exists.

**Comment by gevorggalstyan** [comment]
@Arattian is this a case of the property being `null` but assumed to not exist in the business logic?

**Comment by Arattian** [comment]
Yes, that was the case. The value I've trying to update had "null" value, that's why the dynamodb returned such error. Closing this issue, thank you.
